CREATE TABLE USUARIOS
(
	IDUSUARIO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR(20) UNIQUE,
	PASSWORD VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	FOTO VARCHAR(255),
	DESCRIPCION TEXT,
	TIPO SMALLINT NOT NULL
);
CREATE TABLE POSTS
(
	IDPOST INTEGER PRIMARY KEY AUTO_INCREMENT,
	TITULO VARCHAR(40) NOT NULL,
	USERNAME VARCHAR(20) NOT NULL,
	CUERPO TEXT NOT NULL,
	NUMVISITAS INTEGER NOT NULL,
	FECHA_CREACION DATE NOT NULL,
	CONTESTADA SMALLINT NOT NULL,
	FOREIGN KEY (USERNAME) REFERENCES USUARIOS(USERNAME)
);
CREATE TABLE RESPUESTAS
(
	IDRESPUESTA INTEGER PRIMARY KEY AUTO_INCREMENT,
	USERNAME VARCHAR(20) NOT NULL,
	IDPOST INTEGER NOT NULL,
	CUERPO TEXT NOT NULL,
	FECHA_CREACION DATE NOT NULL,
	FOREIGN KEY (USERNAME) REFERENCES USUARIOS(USERNAME),
	FOREIGN KEY (IDPOST) REFERENCES POSTS(IDPOST)
);
CREATE TABLE TAGS
(
	TAG VARCHAR(20) PRIMARY KEY
);

CREATE TABLE TAGENPOSTS
(
	TAG VARCHAR(20),
	IDPOST INTEGER,
	FOREIGN KEY (IDPOST) REFERENCES POSTS(IDPOST),
	FOREIGN KEY (TAG) REFERENCES TAGS(TAG),
	constraint PK_TAGENPOSTS primary key (IDPOST, TAG)
);

INSERT INTO USUARIOS(IDUSUARIO, USERNAME, PASSWORD, EMAIL, FOTO, DESCRIPCION, TIPO) VALUES (0,"yonyon", "yonyon", "yonyon@gmail.com", "path", "Soy un rogue", 1);
INSERT INTO POSTS(IDPOST, TITULO, USERNAME, CUERPO, NUMVISITAS, FECHA_CREACION, CONTESTADA) VALUES (0,"A title", "yonyon", "Cuerpo del post", 10, 20150124, 0);
INSERT INTO RESPUESTAS(IDRESPUESTA, USERNAME, IDPOST, CUERPO, FECHA_CREACION) VALUES (0,"yonyon", 1, "Cuerpo de la respuesta", 20150124);
INSERT INTO TAGS(TAG) VALUES ("C++");
INSERT INTO TAGENPOSTS(TAG, IDPOST) VALUES ("C++", 1);