CREATE TABLE USERS
(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR(20) UNIQUE,
	PASSWORD VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	FOTO VARCHAR(255),
	DESCRIPCION TEXT,
	TIPO SMALLINT NOT NULL
);
CREATE TABLE POSTS
(
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	TITULO VARCHAR(40) NOT NULL,
	USERNAME VARCHAR(20) NOT NULL,
	CUERPO TEXT NOT NULL,
	NUMVISITAS INTEGER NOT NULL,
	FECHA_CREACION DATE NOT NULL,
	CONTESTADA SMALLINT NOT NULL,
	FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);
CREATE TABLE RESPUESTAS
(
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	USERNAME VARCHAR(20) NOT NULL,
	IDPOST INTEGER NOT NULL,
	CUERPO TEXT NOT NULL,
	FECHA_CREACION DATE NOT NULL,
	FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME),
	FOREIGN KEY (IDPOST) REFERENCES POSTS(ID)
);
CREATE TABLE TAGS
(
	TAG VARCHAR(20) PRIMARY KEY
);

CREATE TABLE TAGENPOSTS
(
	TAG VARCHAR(20),
	ID INTEGER,
	FOREIGN KEY (ID) REFERENCES POSTS(ID),
	FOREIGN KEY (TAG) REFERENCES TAGS(TAG),
	constraint PK_TAGENPOSTS primary key (ID, TAG)
);

INSERT INTO USERS(ID, USERNAME, PASSWORD, EMAIL, FOTO, DESCRIPCION, TIPO) VALUES (0,"yonyon", "yonyon", "yonyon@gmail.com", "path", "Soy un rogue", 1);
INSERT INTO POSTS(ID, TITULO, USERNAME, CUERPO, NUMVISITAS, FECHA_CREACION, CONTESTADA) VALUES (0,"A title", "yonyon", "Cuerpo del post", 10, 20150124, 0);
INSERT INTO RESPUESTAS(ID, USERNAME, IDPOST, CUERPO, FECHA_CREACION) VALUES (0,"yonyon", 1, "Cuerpo de la respuesta", 20150124);
INSERT INTO TAGS(TAG) VALUES ("C++");
INSERT INTO TAGENPOSTS(TAG, ID) VALUES ("C++", 1);